name: Release Node SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the SDKs that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Publish to NPM
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          fern generate --group node-sdk --version ${{ inputs.version }} --log-level debug
